# RESTBase wikimedia example config

# Load some project templates. These are referenced / shared between domains
# in the root_spec further down.
default_project: &default_project
  x-modules:
    - path: projects/wikitolearn.yaml
      options: &default_options
        table:
          backend: sqlite
          dbname: /db/db.sqlite3
          pool_idle_timeout: 20000
          retry_delay: 250
          retry_limit: 10
          show_sql: false
        action:
          apiUriTemplate: "{{'https://{domain}/w/api.php'}}"
        graphoid:
          host: http://graphoid.wikimedia.org
        parsoid:
          host: http://parsoid:8000
        mathoid:
          host: http://mathoid:10044
          # 10 days Varnish caching, one day client-side
          cache-control: s-maxage=864000, max-age=86400
        mobileapps:
          host: http://appservice.wmflabs.org
        related:
          cache_control: s-maxage=86400, max-age=86400
        # 10 days Varnish caching, one day client-side
        purged_cache_control: s-maxage=864000, max-age=86400

wikimedia.org: &wikimedia.org
  x-modules:
    - path: projects/wikimedia.org.yaml
      options:
        <<: *default_options
        pageviews:
          host: https://wikimedia.org/api/rest_v1/metrics

spec_root: &spec_root
  title: "The RESTBase root"
  x-sub-request-filters:
    - type: default
      name: http
      options:
        allow:
          - pattern: /^https?:\/\/[a-zA-Z0-9\.]+\/api\.php/
            forward_headers: true
          - pattern: http://mathoid:10044
            forward_headers: true
          - pattern: http://parsoid:8000
            forward_headers: true
          - pattern: /^https?:\/\//
  paths:
    /{domain:de.wikitolearn.org}: *default_project
    /{domain:pt.wikitolearn.org}: *default_project
    /{domain:sv.wikitolearn.org}: *default_project
    /{domain:meta.wikitolearn.org}: *default_project
    /{domain:fr.wikitolearn.org}: *default_project
    /{domain:pool.wikitolearn.org}: *default_project
    /{domain:it.wikitolearn.org}: *default_project
    /{domain:es.wikitolearn.org}: *default_project
    /{domain:en.wikitolearn.org}: *default_project
    /{domain:de.direct.wikitolearn.org}: *default_project
    /{domain:pt.direct.wikitolearn.org}: *default_project
    /{domain:sv.direct.wikitolearn.org}: *default_project
    /{domain:meta.direct.wikitolearn.org}: *default_project
    /{domain:fr.direct.wikitolearn.org}: *default_project
    /{domain:pool.direct.wikitolearn.org}: *default_project
    /{domain:it.direct.wikitolearn.org}: *default_project
    /{domain:es.direct.wikitolearn.org}: *default_project
    /{domain:en.direct.wikitolearn.org}: *default_project
    /{domain:de.wikitolearn.vodka}: *default_project
    /{domain:pt.wikitolearn.vodka}: *default_project
    /{domain:sv.wikitolearn.vodka}: *default_project
    /{domain:meta.wikitolearn.vodka}: *default_project
    /{domain:fr.wikitolearn.vodka}: *default_project
    /{domain:pool.wikitolearn.vodka}: *default_project
    /{domain:it.wikitolearn.vodka}: *default_project
    /{domain:es.wikitolearn.vodka}: *default_project
    /{domain:en.wikitolearn.vodka}: *default_project
    /{domain:de.tuttorotto.biz}: *default_project
    /{domain:pt.tuttorotto.biz}: *default_project
    /{domain:sv.tuttorotto.biz}: *default_project
    /{domain:meta.tuttorotto.biz}: *default_project
    /{domain:fr.tuttorotto.biz}: *default_project
    /{domain:pool.tuttorotto.biz}: *default_project
    /{domain:it.tuttorotto.biz}: *default_project
    /{domain:es.tuttorotto.biz}: *default_project
    /{domain:en.tuttorotto.biz}: *default_project
    /{domain:de.tuttorotto.eu}: *default_project
    /{domain:pt.tuttorotto.eu}: *default_project
    /{domain:sv.tuttorotto.eu}: *default_project
    /{domain:meta.tuttorotto.eu}: *default_project
    /{domain:fr.tuttorotto.eu}: *default_project
    /{domain:pool.tuttorotto.eu}: *default_project
    /{domain:it.tuttorotto.eu}: *default_project
    /{domain:es.tuttorotto.eu}: *default_project
    /{domain:en.tuttorotto.eu}: *default_project
    /{domain:de.tuttorotto.org}: *default_project
    /{domain:pt.tuttorotto.org}: *default_project
    /{domain:sv.tuttorotto.org}: *default_project
    /{domain:meta.tuttorotto.org}: *default_project
    /{domain:fr.tuttorotto.org}: *default_project
    /{domain:pool.tuttorotto.org}: *default_project
    /{domain:it.tuttorotto.org}: *default_project
    /{domain:es.tuttorotto.org}: *default_project
    /{domain:en.tuttorotto.org}: *default_project
    /{domain:de.tuttorotto.it}: *default_project
    /{domain:pt.tuttorotto.it}: *default_project
    /{domain:sv.tuttorotto.it}: *default_project
    /{domain:meta.tuttorotto.it}: *default_project
    /{domain:fr.tuttorotto.it}: *default_project
    /{domain:pool.tuttorotto.it}: *default_project
    /{domain:it.tuttorotto.it}: *default_project
    /{domain:es.tuttorotto.it}: *default_project
    /{domain:en.tuttorotto.it}: *default_project

    /{domain:wikimedia.org}: *wikimedia.org

    # A robots.txt to make sure that the content isn't indexed.
    /robots.txt:
      get:
        x-request-handler:
          - static:
              return:
                status: 200
                headers:
                  content-type: text/plain
                body: |
                  User-agent: *
                  Allow: /*/v1/?doc
                  Disallow: /
# Finally, a standard service-runner config.
info:
  name: restbase

services:
  - name: restbase
    module: hyperswitch
    conf: 
      port: 7231
      spec: *spec_root
      salt: secret
      default_page_size: 125
      user_agent: RESTBase

logging:
  name: restbase
  level: info
  #streams:
  #- type: gelf
  #  host: <%= @logstash_host %>
  #  port: <%= @logstash_port %>
